type AnyObj = Record<string, any>;

export const defaultSiteSettings: AnyObj = {
  logo: { url: '', alt: 'Site Logo', width: 200, height: 60 },
  siteName: '',
  logoText: '',
  slogan: '',
  description: '',
  colors: { primary: '#003450', secondary: '#075985', accent: '#0369a1' },
  socialMedia: { linkedin: '', twitter: '', github: '', instagram: '' },
  seo: { metaTitle: '', metaDescription: '', keywords: [] },
  contact: { email: '', phone: '', address: '' },
  siteUrl: '',
  timezone: 'Europe/Istanbul',
  language: 'tr',
  favicon: '',
  maintenanceMode: false,
  allowRegistration: true,
  enableComments: true,
  analytics: {
    googleAnalyticsId: '',
    googleTagManagerId: '',
    googleSiteVerification: '',
    enableAnalytics: false,
  },
  system: { maxUploadSize: 10 },
  themeConfig: {
    colors: {
      primary: '#003450',
      secondary: '#3A506B',
      accent: '#003450',
      background: '#F8F9FA',
      text: '#3D3D3D',
      textLight: '#6B7280',
      white: '#FFFFFF',
      black: '#000000',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
    },
    typography: {
      fonts: { heading: 'Inter', body: 'Inter', button: 'Inter', nav: 'Inter' },
      sizes: { h1: '3rem', h2: '2.5rem', h3: '2rem', h4: '1.5rem', h5: '1.25rem', h6: '1rem', body: '1rem', small: '0.875rem', tiny: '0.75rem' },
      weights: { light: '300', normal: '400', medium: '500', semibold: '600', bold: '700', extrabold: '800' },
      lineHeights: { tight: '1.25', normal: '1.5', relaxed: '1.75', loose: '2' },
    },
    hero: { enabled: true, height: '80vh', minHeight: '600px', backgroundColor: 'linear-gradient(135deg, #003450 0%, #3A506B 100%)' },
    buttons: {},
    cards: {},
    navigation: {},
    forms: {},
    layout: { maxWidth: 1280, sidebar: false, headerStyle: 'fixed', footerStyle: 'simple', containerPadding: '1.5rem', sectionPadding: '5rem 0' },
    features: { heroSlider: true, portfolioGrid: true, blogList: true, contactForm: true },
    footer: { backgroundColor: '#0f1b26', textColor: '#94a3b8', headingColor: '#FFFFFF', linkColor: '#cbd5e1', linkHoverColor: '#FFFFFF', accentColor: '#3B82F6', borderColor: 'rgba(255,255,255,0.1)' },
    spacing: { xs: '0.25rem', sm: '0.5rem', md: '1rem', lg: '1.5rem', xl: '2rem', '2xl': '3rem', '3xl': '4rem' },
    fonts: { heading: 'Inter', body: 'Inter' },
  },
  seoConfig: {
    metaTitleSuffix: ' | Fixral',
    globalMetaDescription: '',
    globalKeywords: [],
    enableSchemaMarkup: true,
    enableOpenGraph: true,
    enableTwitterCards: true,
  },
  analyticsConfig: {
    googleAnalyticsId: '',
    googleTagManagerId: '',
    googleSiteVerification: '',
    enablePageViewTracking: true,
  },
  socialMediaConfig: {
    twitter: '',
    instagram: '',
    linkedin: '',
    github: '',
    facebook: '',
    youtube: '',
    enableSharing: true,
    showShareCount: false,
  },
  isActive: true,
};

export const defaultFooterSettings: AnyObj = {
  mainDescription:
    'Mühendislik ve teknoloji alanında yenilikçi çözümler sunarak projelerinizi hayata geçiriyoruz.',
  contactInfo: {
    email: 'erdem.erciyas@gmail.com',
    phone: '+90 (500) 123 45 67',
    address: 'Teknoloji Vadisi, Ankara, Türkiye',
  },
  quickLinks: [
    { title: 'Anasayfa', url: '/', isExternal: false },
    { title: 'Hizmetler', url: '/services', isExternal: false },
    { title: 'Projeler', url: '/portfolio', isExternal: false },
    { title: 'İletişim', url: '/contact', isExternal: false },
  ],
  socialLinks: {
    linkedin: '',
    twitter: '',
    instagram: '',
    facebook: '',
    github: '',
    youtube: '',
  },
  copyrightInfo: {
    companyName: 'FIXRAL',
    year: new Date().getFullYear(),
    additionalText: 'Tum Haklari Saklidir.',
  },
  developerInfo: {
    name: 'Erdem Erciyas',
    website: 'https://www.erdemerciyas.com.tr',
    companyName: 'Erciyas Engineering',
  },
  visibility: {
    showQuickLinks: true,
    showSocialLinks: true,
    showContactInfo: true,
    showDeveloperInfo: true,
  },
  theme: {
    backgroundColor: 'bg-slate-800',
    textColor: 'text-slate-300',
    accentColor: 'text-brand-primary-400',
  },
};
